# Generated by Buildr 1.4.22, change to your liking
# Standard maven2 repository
repositories.remote << 'http://repo1.maven.org/maven2'

define 'wftest.server' do
  project.group = 'wftest'
  project.version = '1.31.0-buildr'

  JEE7 = 'javax:javaee-api:jar:7.0'

  define 'wftest.server.ear' do
    package(:ear).add project('wftest.common')
    package(:ear).add :ejb=>project('wftest.server.acre')
    package(:ear).add :ejb=>project('wftest.server.ejb')
    package(:ear).add :war=>project('wftest.server.backend.web'), :context_root=>'eu/backend', :path=>''
    package(:ear).include _('src/main/application/META-INF')
  end

  define 'wftest.server.ejb' do
    compile.with 	JEE7,
        					project('wftest.common'),
        					project('wftest.server.acre')
    package :jar
  end

  define 'wftest.common' do
    compile.with JEE7
    package :jar#, :id => 'wftest.common'
  end

  define 'wftest.server.acre' do
    compile.with  JEE7,
					        project('wftest.common')
    package :jar
  end

  define 'wftest.server.backend.web' do
    compile.with  JEE7,
                	project('wftest.common'),
                	project('wftest.server.ejb')
    package(:war).with :libs=>[]
  end

end
